version: "3.9"
services:
  db:
    container_name: next-barcode-pet-postgres
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: next-barcode-pet
  
  app:
    depends_on:
      - db
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app  # Bind mount for hot reload
      - /app/node_modules  # Prevents overwriting container node_modules
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
    command: "npm run dev"
